config/routes.rb
Rails.application.routes.draw do
  get  'ilms/login'
  post 'ilms/login'

  get  'ilms/lessons/:course_id', to: 'ilms#lessons_for_course'
  post 'ilms/create_lesson', to: 'ilms#create_lesson'
  post 'ilms/open_lesson',   to: 'ilms#open_lesson'
  post 'ilms/close_lesson',  to: 'ilms#close_lesson'
  post 'ilms/show_lesson',   to: 'ilms#show_lesson'
  post 'ilms/hide_lesson',  to: 'ilms#hide_lesson'
  post 'ilms/create_course', to: 'ilms#create_course'
  post 'ilms/create_teacher', to: 'ilms#create_teacher'
  get  'ilms/teacher',       to: 'ilms#teacher'
  get  'ilms/course',        to: 'ilms#course'
  get  'ilms/courses',        to: 'ilms#courses'
  get  'ilms/chapters_for_course', to: 'ilms#chapters_for_course'
  get  'ilms/couch_creds',        to: 'ilms#couch_creds'

  get  'ilms/logout'

  devise_for :teachers
  get 'catalog/books'

  get 'catalog/books/:book_ident/chapters', to: 'catalog#chapters'

  get 'catalog/books/:book_ident/chapters/:chapter_id/lessons', to: 'catalog#lessons'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  root 'welcome#index'

  resources :lessons
  resources :students
  get 'students/set_name/:student_number', to: 'students#set_name'
  get 'students_collection', to: 'students#students_collection'
  get 'students_collection_from_alt_names', to: 'students#students_collection_from_alt_names'
  get 'students_in_course/:course_id', to: 'students#students_in_course'

  get '/work/:lesson_id', to: 'work#show'
  get '/work/:lesson_id/item-done/:item_id', to: "work#item_done"
  get '/work/:lesson_id/view-progress', to: 'work#view_progress'
  post '/signin-student', to: 'signin_student#signInOrCreate'

  post '/work/:lesson_id', to: 'work#show'

  get '/work/:lesson_id/own_progress', to: 'work#own_progress'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # @lessons = Lesson.all
    # @lessons.to_a.sort_by! {|lesson| lesson.chapter.title}
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.slim
div class="jumbotron"
  div class="container"
    h1 Fliptcc
    h2 Language content and question items in class or at home.
    div class="well"
      p
        | Students can use their own devices to access content in class. No need for complicated logins. Students can get started quickly and work at their own pace, alone or in groups.
      p
        | Use it to instead of PowerPoint to present content to students. Then review the material together as a class. For example, in a Present-Practice-Produce classroom, you may let students work for 30 minutes, then review together for 20 minutes in a 50 minute period. This can count as the Present and Practice phases. Then you can spend the second period on Production.
      p
        = link_to('Try It!', new_teacher_registration_path, :class => 'btn btn-large btn-primary')

<div class="container welcome-content">
  <!-- Example row of columns -->
  <div class="row">
    h3
      | Take a look at these 
      a<> href="/catalog/books/" samples
      | or read on to find out more.
    <div class="welcome-samples">
      <div class="media">
        <div class="media-left">
          <a href="/catalog/books/get-into-english/chapters">
            <img class="media-object" src="/images/get-into-english-cover.png" alt="..." width="100">
          </a>
        </div>
        <div class="media-body">
          h4 class="media-heading" 
            a href="/catalog/books/get-into-english/chapters" Get into English
          | Get into English, 曹嘉秀.方淑慧等, All-People Publishing, 2015, 978-986-5765-12-5.
        </div>
        <div class="media">
        <div class="media-left">
          <a href="/catalog/books/english-power-at-work/chapters">
            <img class="media-object" src="/images/english-power-at-work-cover.jpg" alt="..." width="100">
          </a>
        </div>
        <div class="media-body">
          h4 class="media-heading" 
            a href="/catalog/books/english-power-at-work/chapters" English Power at Work
          | English Power @ Work, 曹家秀, AMC Publishing Company, 2015, 978-986-5965-72-3.
        </div>
      </div>
    </div>
  </div> <!-- /row sample -->
  <hr>
  div class="row"
    h1 Step One
    div class="container"
      p Share your URL with students

      p For example:
      div class="welcome-example-url"
        | http://fliptcc.herokuapp.com/work/26
      p You might put this link on the e-learning system, or use a LINE group.

  div class="row"
    h1 Step Two
    div class="container"
      p Students access the site on their web browser and enter their information.

      p For example:
      div class="welcome-student-login-img-container welcome-img-container"
        img src="/images/intro/student-login.png"

  div class="row"
    h1 Question types
    div class="container"
      p
        | There are several forms of content and question types. Simple listening, Listen and Copy, Listening Mulitple Choice, and Fill in the Blank.
    h2  Simple Listening
    div class="container"
      p
        | The student clicks on the dialog to listen.  When the audio has finished playing, a green check
        span<> class="welcome-green-check" [✓]
        | will appear to show this item is finished.
  div class="row"
    div class="container"
      div class="welcome-double-img-container"
        div class="welcome-img-container-outer"
          div class="welcome-img-container"
            img src="/images/intro/simple-listening-1.png"
        div class="welcome-img-container-outer"
          div class="welcome-img-container"
            img src="/images/intro/simple-listening-2.png"

  div class="row"
    h2 Listen and Copy 「聽寫」
    div class="container"
      p There is a dictal-listening type. Students must listen and write what they hear. In this example, students must copy the question they hear. When they finish writing correctly, a checkmark will appear. Later, they will answer the question in a mulitple choice item.
  div class="row"
    div class="container"
      div class="welcome-double-img-container"
        div class="welcome-img-container-outer"
          div class="welcome-img-container"
            img src="/images/intro/listen-and-copy-1.png"
        div class="welcome-img-container-outer"
          div class="welcome-img-container"
            img src="/images/intro/listen-and-copy-2.png"

  div class="row"
    div class="container"
      h3 
        strong Instant feedback:
      p If students make a mistake along the way, the input box will become red to show they have a mistake.
  div class="row"
    div class="container"
      div class="welcome-double-img-container"
        div class="welcome-img-container-outer"
          div class="welcome-img-container"
            img src="/images/intro/listen-and-copy-3.png"
        div class="welcome-img-container-outer"
          div class="welcome-img-container"
            img src="/images/intro/listen-and-copy-4.png"


  div class="row"
    h2 Listening Multiple Choice Question 單選題
    div class="container"
      p After writing the question that they heard, students can then actually answer the question.
  div class="row"
    div class="container"
      div class="welcome-double-img-container"
        div class="welcome-img-container-outer"
          div class="welcome-img-container"
            img src="/images/intro/listen-mcq-1.png"
        div class="welcome-img-container-outer"
          div class="welcome-img-container"
            img src="/images/intro/listen-mcq-2.png"

  div class="row"
    div class="container"
      h3 
        strong Instant feedback:
      p If student get the wrong answer, the app will play the question again and the student can have a second chance.
  div class="row"
    div class="container"
      div class="welcome-double-img-container"
        div class="welcome-img-container-outer"
          div class="welcome-img-container"
            img src="/images/intro/listen-mcq-3.png"
        div class="welcome-img-container-outer"
          div class="welcome-img-container"
            img src="/images/intro/listen-mcq-4.png"

  div class="row"
    h2 Fill in the blanks 「填空」
    div class="container"
      p Another question type is fill-in-the-blank with a word bank.
  div class="row"
    div class="container"
      div class="welcome-img-container-outer"
        div class="welcome-img-container"
          img src="/images/intro/fill-in-the-blanks.png"

  div class="row"
    h2 Progress Bar
    div class="container"
      p  The bottom of the page shows the student’s progress through the lesson.
         In this picture, you can see the student has finished 22% of the lesson.
  div class="row"
    div class="container"
      div class="welcome-img-container-outer"
        div class="welcome-img-container"
          img src="/images/intro/progress-bar.png"

  div class="row"
    h2 Evaluation
    div class="container"
      p The teacher can monitor the progress of students. A green rectangle and check means finished. A red rectangle means not yet finished. If many students miss one problem, the teacher can address this in class.
  div class="row"
    div class="container"
      div class="welcome-img-container-outer"
        div class="welcome-img-container welcome-evaluation-img-container"
          img src="/images/intro/evaluation.png"
  div class="row"
    h2 About
    div class="container"
      p The inspiration for this app was the flipped classroom model of education. In a flipped classroom, students listen to a lecture at home with the class time reserved as a workshop type activity.  Instead of a lecture, the app presents material in an interactive way. I think it is better than a lecture because it covers the same material as a lecture would, but in a way that allows students to work at their own pace and review as many times as they wish. It is also more time efficient because there is no need for long explanations.
      p In my case, students are busy with other school work, or perhaps jobs, and don’t have time to spend previewing extensively at home. So, I have them do the work in class. I have found using this has increased student involvement and helped students understand better. It also increased the amount and quality of questions that students asked the teacher, so the teacher could help more effectively. 

      p The method I have used is to let students try the app their own for the first 30 minutes of class and as they work, ask questions. Then in the final 20 minutes of the period, review the material together as a class. This has increased the speed at which I can cover material and has made room for other activities, such as speaking and writing.

      p Another way to use it would be to cover the material in class quickly, in about 15 minutes, without giving the full answers. Then have students work independently for 25 minutes, working at their own pace and asking questions. Then review together for 10 minutes at the end.

      p It is my hope that other teachers might also find this method useful to complement their own teaching styles.
  <hr>

  footer
    p &copy; Fooyin 2015
  footer
</div> <!-- /container -->