config/routes.rb
Rails.application.routes.draw do
  get  'ilms/login'
  post 'ilms/login'

  get  'ilms/lessons/:course_id', to: 'ilms#lessons_for_course'
  post 'ilms/create_lesson', to: 'ilms#create_lesson'
  post 'ilms/open_lesson',   to: 'ilms#open_lesson'
  post 'ilms/close_lesson',  to: 'ilms#close_lesson'
  post 'ilms/show_lesson',   to: 'ilms#show_lesson'
  post 'ilms/hide_lesson',  to: 'ilms#hide_lesson'
  post 'ilms/create_course', to: 'ilms#create_course'
  post 'ilms/create_teacher', to: 'ilms#create_teacher'
  get  'ilms/teacher',       to: 'ilms#teacher'
  get  'ilms/course',        to: 'ilms#course'
  get  'ilms/courses',        to: 'ilms#courses'
  get  'ilms/chapters_for_course', to: 'ilms#chapters_for_course'
  get  'ilms/couch_creds',        to: 'ilms#couch_creds'

  get  'ilms/logout'

  devise_for :teachers
  get 'catalog/books'

  get 'catalog/books/:book_ident/chapters', to: 'catalog#chapters'

  get 'catalog/books/:book_ident/chapters/:chapter_id/lessons', to: 'catalog#lessons'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  root 'welcome#index'

  resources :lessons
  resources :students
  get 'students/set_name/:student_number', to: 'students#set_name'
  get 'students_collection', to: 'students#students_collection'
  get 'students_collection_from_alt_names', to: 'students#students_collection_from_alt_names'
  get 'students_in_course/:course_id', to: 'students#students_in_course'

  get '/work/:lesson_id', to: 'work#show'
  get '/work/:lesson_id/item-done/:item_id', to: "work#item_done"
  get '/work/:lesson_id/view-progress', to: 'work#view_progress'
  post '/signin-student', to: 'signin_student#signInOrCreate'

  post '/work/:lesson_id', to: 'work#show'

  get '/work/:lesson_id/own_progress', to: 'work#own_progress'
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  before_action :set_books
  before_action :set_book, :only => [:chapters, :lessons]
  def books
      respond_to do |format|
        format.json { render :json => @books }
        format.html {render}
      end
  end

  def chapters
      @chapters = Chapter.all.select{|c| c.book_ident == @book_ident}
      # @chapters.sort! {|x,y| x.title <=> y.title}
      # All this does is sort by title but, make 2 come before 10
      @chapters.sort_by! do |x|
         title = x.title
         numbers = title.split(" ")
         arr = numbers.map do |word|
           if word.to_i > 0
             "%03d" % word.to_i
           else
             word
           end
         end
         arr.join(" ")
      end

      respond_to do |format|
        format.html {render}
        format.json { render :json => @chapters }
      end
  end

  def lessons
    lesson_params = params.permit(:book_ident, :chapter_id)
    @chapter = Chapter.fetch lesson_params[:chapter_id].to_i
    if current_teacher
      @lessons = Lesson.where(:chapter_id => lesson_params[:chapter_id], :teacher => current_teacher)
    else
      @lessons = Lesson.where(:chapter_id => lesson_params[:chapter_id], :teacher => nil)  # for demo
    end
    @completed = []
  end

  private
  def set_books
    # list books
    # We just have two books, so we won't create a model just yet.
    @books = [{'title' => 'Get into English',
               'ident' => 'get-into-english',
               'img_src' =>'/images/get-into-english-cover.png',
               'blurb' => 'Get into English, 曹嘉秀.方淑慧等, All-People Publishing, 2015, 978-986-5765-12-5.'
              },
              {'title'  => 'English Power at Work',
               'ident' => 'english-power-at-work',
               'img_src' => '/images/english-power-at-work-cover.jpg',
               'blurb' => 'English Power @ Work, 曹家秀, AMC Publishing Company, 2015, 978-986-5965-72-3.'
              },
              {'title'  => 'Lets Talk 2',
               'ident' => 'lets-talk-2',
               'img_src' => '/images/lets-talk-2-cover.png',
               'blurb' => 'Jones, Leo, Lets Talk 2, Cambridge UP',
               'private' => true
              },
              {'title'  => 'Rodney vs. Death',
               'ident' => 'rodney-vs-death',
               'img_src' => '/images/lets-talk-2-cover.png',
               'blurb' => 'TAL',
               'private' => false
              }
    ]
  end
  def set_book
      book_params = params.permit(:book_ident)
      @book_ident = book_params[:book_ident]
      book_index = @books.find_index {|b| b['ident'] == @book_ident}
      @book = @books[book_index]
  end
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/views/catalog/books.html.erb
<div class="container">
  <h1>Books</h1>

  <% @books.each do |book| %>
    <div class="media">
    <div class="media-left">
      <a href="/catalog/books/<%=book['ident']%>/chapters">
        <img class="media-object" src="<%=book['img_src']%>" alt="..." width="100">
      </a>
    </div>
    <div class="media-body">
      <h4 class="media-heading">
        <a href="/catalog/books/<%=book['ident']%>/chapters">
          <%=book['title']%>
        </a>
      </h4>
        <%=book['blurb']%>
    </div>
  </div>
  <% end %>
</div>

app/views/catalog/chapters.html.erb
<div class="container">
  <h1>Chapters for <%=@book['title']%></h1>
  <!-- Example row of columns -->
  <div class="row">
      <div class="panel panel-fliptcc">
          <div class="panel-heading">Chapters for <%=@book['title']%></div>
          <div class="panel-body">
            <div class="list-group">
              <%if @chapters%>
              <% @chapters.each do |chapter|%>
                <a class="list-group-item" href="/catalog/books/<%=@book['ident']%>/chapters/<%=chapter.id%>/lessons">
                    <%=chapter.title%>

                  <% if current_teacher %>
                    <% lessons_count = chapter.lessons_count(current_teacher) %>
                    <%if lessons_count > 0%>
                      <span class="badge">
                        <%= lessons_count %>
                      </span>
                    <% end %>
                  <% end %>
                </a>
              <% end %>
              <% end %>
            </div>
          </div>
      </div> <!-- /panel -->
      <a href='/catalog/books'>Back</a>
  </div> <!-- /row -->

  <hr>

  <footer>
    <p>&copy; Fooyin 2015</p>
  </footer>
</div> <!-- /container -->

app/views/catalog/lessons.html.erb
<div class="container">
  <h1>Lessons</h1>
  <!-- Example row of columns -->
  <div class="row">
      <div class="panel panel-fliptcc">
        <div class="panel-heading">
          <% if !current_teacher %> Sample <%end%>
           Lessons for <%=@chapter.title%> </div>
          <div class="panel-body">
            <div class="list-group">
              <%if @lessons%>
                <% @lessons.each do |lesson|%>
                  <%if !current_teacher %>
                    <div class="list-group-item" href="/work/<%=lesson.id%>">
                      <a class="badge" href="/work/<%=lesson.id%>/view-progress">
                        progress: <%= lesson.students_count%>
                      </a>
                      <a href="/work/<%=lesson.id%>">
                        <%=@chapter.title%> | <%=lesson.title%> 
                        <% if lesson.code %>
                           <%= lesson.code %>
                        <%end%>
                      </a>
                    </div>
                  <%end%>
                  <%if current_teacher %>
                    <a class="list-group-item" href="<%=url_for lesson%>">
                      <span class="badge">
                        <%= lesson.students_count%>
                      </span>
                        <%=@chapter.title%> | <%=lesson.title%> 
                        <% if lesson.code %>
                           <%= lesson.code %>
                        <%end%>
                    </a>
                  <%end%>

                <% end %>
              <% end %>
              <% if current_teacher %>
                <a class="list-group-item" href="/lessons/new?chapter_id=<%= @chapter.id %>">
                  Add lesson + 
                </a>
              <% end %>
            </div>
          </div>
      </div> <!-- /panel -->
      <a href='/catalog/books/<%=@book['ident']%>/chapters'>Back</a>
        <% if !current_teacher %>
          <span class="pull-right alert alert-danger"> You are not logged in, but you may view these sample lessons. <a class="btn btn-default" href="<%=new_teacher_session_path%>">Teacher Login</a> </span>
        <% end %>
  </div> <!-- /row -->

  <hr>

  <footer>
    <p>&copy; Fooyin 2015</p>
  </footer>
</div> <!-- /container -->