config/routes.rb
Rails.application.routes.draw do
  get  'ilms/login'
  post 'ilms/login'

  get  'ilms/lessons/:course_id', to: 'ilms#lessons_for_course'
  post 'ilms/create_lesson', to: 'ilms#create_lesson'
  post 'ilms/open_lesson',   to: 'ilms#open_lesson'
  post 'ilms/close_lesson',  to: 'ilms#close_lesson'
  post 'ilms/show_lesson',   to: 'ilms#show_lesson'
  post 'ilms/hide_lesson',  to: 'ilms#hide_lesson'
  post 'ilms/create_course', to: 'ilms#create_course'
  post 'ilms/create_teacher', to: 'ilms#create_teacher'
  get  'ilms/teacher',       to: 'ilms#teacher'
  get  'ilms/course',        to: 'ilms#course'
  get  'ilms/courses',        to: 'ilms#courses'
  get  'ilms/chapters_for_course', to: 'ilms#chapters_for_course'
  get  'ilms/couch_creds',        to: 'ilms#couch_creds'

  get  'ilms/logout'

  devise_for :teachers
  get 'catalog/books'

  get 'catalog/books/:book_ident/chapters', to: 'catalog#chapters'

  get 'catalog/books/:book_ident/chapters/:chapter_id/lessons', to: 'catalog#lessons'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  root 'welcome#index'

  resources :lessons
  resources :students
  get 'students/set_name/:student_number', to: 'students#set_name'
  get 'students_collection', to: 'students#students_collection'
  get 'students_collection_from_alt_names', to: 'students#students_collection_from_alt_names'
  get 'students_in_course/:course_id', to: 'students#students_in_course'

  get '/work/:lesson_id', to: 'work#show'
  get '/work/:lesson_id/item-done/:item_id', to: "work#item_done"
  get '/work/:lesson_id/view-progress', to: 'work#view_progress'
  post '/signin-student', to: 'signin_student#signInOrCreate'

  post '/work/:lesson_id', to: 'work#show'

  get '/work/:lesson_id/own_progress', to: 'work#own_progress'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :lesson_progresses, dependent: :destroy
  belongs_to :course
  belongs_to :teacher
  def chapter
    if chapter_id
      return Chapter.fetch chapter_id
    else
      return nil
    end
  end
  def students_count
    Lesson.count_by_sql "SELECT COUNT(DISTINCT student_id) FROM lesson_progresses WHERE lesson_id=#{self.id.to_i}"
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_teacher!

  # GET /lessons
  # GET /lessons.json
  def index
    lp = params.permit(:chapter_id)
    if lp['chapter_id']
      chapter_id = lp['chapter_id']
      @chapter = Chapter.fetch chapter_id
      @lessons = Lesson.where :teacher_id => current_teacher.id, :chapter_id => chapter_id
    else
      @lessons = Lesson.where :teacher_id => current_teacher.id
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @student = Student.find params[:id]
  end

  # GET /lessons/new
  def new
    lp = params.permit(:chapter_id)
    if lp['chapter_id']
      @chapter_id = lp['chapter_id']
    end
    @lesson = Lesson.new
    @chapters = Chapter.all_as_hashes
  end

  # GET /lessons/1/edit
  def edit
    @chapters = Chapter.all_as_hashes
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    @lesson.teacher = current_teacher
    # TODO: add courses to website frontend
    # have a guest course
    if @lesson.course_id.nil?
      @lesson.course_id = 1
    end

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.fetch(:lesson, {}).permit(:code, :chapter_id, :title)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.slim
.container
  = form_for(lesson) do |f|
    - if lesson.errors.any?
      div id="error_explanation"
        h2 = pluralize(lesson.errors.count, "error") << "prohibited this lesson from being saved:"

        ul
          - lesson.errors.full_messages.each do |message|
            li = message

    .actions
      / = f.label :code
      / = f.text_field :code
      h2 Step 1
      p Name your lesson. For example, name it for the class or date you plan on giving it.
      = f.label :title
      = f.text_field :title
      h2 Step 2
      p Choose which chapter the lesson consists of.
      p
        - if default_chapter_id
          = f.select :chapter_id, options_for_select(@chapters.map{|i| [i['book'] + ' ' + i['chapter'], i['id']]}.sort, default_chapter_id)
        -else
          = f.select :chapter_id, options_for_select(@chapters.map{|i| [i['book'] + ' ' + i['chapter'], i['id']]}.sort, lesson.chapter_id)
      br
      p
        = f.submit

app/views/lessons/_item_edit_audio_picture.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">Audio Picture</div>
  <div class="panel-body">
<%= form_for :item do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :audio_url %>
  <%= f.text_field :audio_url %>
  <%= f.label :picture_url %>
  <%= f.text_field :picture_url %>
<%end%>
</div>
</div>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson, default_chapter_id: @lesson.chapter.id %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.slim
.container
  - if @chapter
    h1 
      | Lessons for "
      =@chapter.title
      | "
  - else
    h1 Your Lessons

  <table class="table">
    <thead>
      <tr>
        <th> Title </th>
        <th> Entry Code </th>
        <th> Chapter </th>
        <th colspan="3"> Actions </th>
      </tr>
    </thead>

    <tbody>
      - @lessons.each do |lesson|
        tr
          td = lesson.title
          td = lesson.code
          td = lesson.chapter.title
          td = link_to 'Show', lesson
          td = link_to 'Edit', edit_lesson_path(lesson)
          td = link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }
    </tbody>
  </table>

  <br>

  = link_to 'New Lesson', new_lesson_path

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson, default_chapter_id: @chapter_id %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.slim
.container

  h1= @lesson.title
  br
  .container
    div 
    a href="/work/#{@lesson.id}" Student link:
    div class="welcome-example-url"
      ="https://fliptcc.herokuapp.com/work/#{@lesson.id}"

    .container.show-lesson-check-students-progress
      
        a.btn.btn-default href="/work/#{@lesson.id}/view-progress" 
          span Check student progress
          span &nbsp;
          span class="badge" =@lesson.students_count

        a.btn.btn-default href="/work/#{@lesson.id}/view-progress/?csv=true" 
          span Export Scores as CSV tabs
          span &nbsp;
          span class="badge" =@lesson.students_count

  = link_to 'Edit', edit_lesson_path(@lesson)
  span<> |
  = link_to 'Back', lessons_path
  hr
    = link_to 'Delete', @lesson, method: :delete, data: { confirm: 'Are you sure you want to delete this lesson? You cannot get it back after you delete.' }, :class=> 'btn btn-danger'